stages:
  - build
  - upload


build1:
  stage: build
  image: debian:buster
  script:
    - apt-get -y update
    - apt-get -y upgrade
    - apt-get -y install build-essential debhelper fakeroot
    - ./debian/rules binary
    - mv ../*.deb .
  artifacts:
    paths:
    - ./*.deb
    expire_in: 10 days


upload:
  image: curlimages/curl:latest
  stage: upload
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file joyent-mdata-client_0.0.1-1_amd64.deb "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mdata-client/0.0.1/joyent-mdata-client_0.0.1-1_amd64.deb"'
